spring.application.name=proyecto
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BDFarmacia;encrypt=false;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=sa
spring.datasource.password=fabri121819
spring.jpa.show-sql=true
spring.jpa.database=sql_server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
jwt.secret=58554a3fb1050342fc78fcb283104faaf8b831ff13af9c633b68c55ce6ab67dd
jwt.expiration=3600000

