spring.application.name=proyecto
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BDFarmacia;encrypt=false;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=sa
spring.datasource.password=123456
spring.jpa.show-sql=true
spring.jpa.database=sql_server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
