package org.luis.proyecto.infrastructure.rest.request;
import java.time.LocalDateTime;

public record ClienteRequest(
    String clienDescripcion,
    String clienRazSoc,
    String clienNomCor,
    String clienSiglas,
    Integer tipDocIdenId,
    String clienDoc,
    String clienRegCom,
    String clienDireccion,
    String clienTelef01,
    String clienTelef02,
    String clienFax,
    String clienCelular,
    String clienMail,
    String clienWeb,
    String clienContacto,
    LocalDateTime clienFecIng,
    String clienEstado,
    String clienGiro,
    LocalDateTime clienUltVta,
    Long ctaCteId,
    String dptoGeoId,
    String provGeoId,
    String distGeoId,
    String usrSistema,
    LocalDateTime fecSistema,
    String hrsSistema
) {}
