package org.luis.proyecto.infrastructure.rest.response;
import java.math.BigDecimal;
import java.time.LocalDateTime;
public record DetalleVentaResponse(
    Integer id,
    String empresaId,
    Integer unidComId,
    String docId,
    String vtaCabNumComp,
    Integer iteAlmId,
    Integer vtaDetCodref,
    String vtaDetItem,
    BigDecimal vtaDetCantidad,
    BigDecimal vtaDetPrecUnit,
    BigDecimal vtaDetValorVta,
    BigDecimal vtaDetValIGV,
    BigDecimal vtaDetValISC,
    BigDecimal vtaDetValTot,
    Integer tipVtaId,
    Integer tipAlmId,
    Integer almacenId,
    Integer vtaDetFracUni,
    Integer vtaDetCantFrac,
    String usrSistema,
    LocalDateTime fecSistema,
    String hrsSistema,
    BigDecimal vtaDetValIna
) {}